---
title: 'Homework #7'
author: "Henry Chen and Lange Kaupinen"
date: "March 21, 2018"
output: word_document
---

```{r, include=FALSE}
# Load Libraries
library(quantmod)
library(TTR)
library(dplyr)
library(plyr)
library(tidyverse)
library(tidyr)
library(rbokeh)
library(ggplot2)
library(shiny)
library(shinydashboard)
library(lubridate)
library(readr)
library(stringr)
library(purrr)
library(magrittr)
library(modelr)
```

Please have an outline in RMarkdown for your project with the topic, data source, and an overview for what you plan to do for your project as well as a timeline.  Identify who (if anyone) you are working with and how you plan to divide the work.  What question do you plan to answer?

**Topic**  
Backtesting Asset Class Strategies in Shiny using the Simple Moving Average (SMA) and Relative Strength Index (RSI)

**Data Source**  
Quantmod

**Overview**  
The SMA is a commonly used tool of Trend-Following funds. As the name suggests, these funds attempt to "ride the trend" of asset class movements (both on the way up and down) by taking both long- and short- positions. Signals, generated using a systematic trading approach centered on a pre-defined SMA (or SMAs), determine when the fund both enters and exits a position. In its truest form, the strategy attempts to avoid large-drawdowns, minimize volatility, and consistently have a low to zero correlation with any specific single asset class.

At odds with Trend-Followers are Counter-Trend Strategies. These funds attempt to anticipate changes in the underlying trend by use of the RSI. When using this strategy, a sell signal is generated by a high reading of the RSI (indicating an "overbought" asset), while a low reading would indicate the asset is poised to reverse its downward trend. The RSI is bound between 0-100 with readings above 70 considered high (and > extreme), and below 30 low (< 20 extreme).

In the Shiny app, we will attempt to evaluate various Trend-Following as well as Counter-Trend strategies using popular portfolio metrics such as maximum drawdown, absolute and relative (i.e., Sharpe Ratio) return, and rolling annualized volatility.

*Proposed asset classes to be tested in the Shiny app:*  

US large- and small-cap stocks  
Developed market (non U.S.) stocks  
Emerging Market Stocks  
U.S. Total Bond Market  
U.S. Treasuries  
U.S. Investment Grade Bonds  
U.S. High-Yield Bonds  
Real Estate Investment Trusts (REITs)  
Mortgage REITs  
Commodities  
Precious Metals  
Cryptocurrencies  

**Timeline**  
We are currently in the research stage and moving towards the initial development of our Shiny app. The app will be in production within three to four weeks. This will allow for two weeks of backtesting, at which point we will proceed to our project write-up and final presentation. 

**Identify who (if anyone) you are working with and how you plan to divide the work**  
Henry Chen. We plan to divide the work evenly. This very similar to the approach we used last semester when we created a Rolling Portfolio Backtesting Engine in the Statistical Programming with R course. More specifically, we will collaborate closely when conducting the background research, statistical programming, findings and conclusions, write-up, and presentation.

**What question do you plan to answer?**  
Can tools such as the SMA and RSI be used to build superior (both on an absolute and risk-adjusted basis) trading strategies when compared to a relative "buy and hold" benchmark.